function f = equilibriumCurve(a,b,c,l_1,psi,theta_2)
%equilibriumCurve
%    X = equilibriumCurve(A,B,C,L_1,PSI,THETA_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Feb-2022 09:43:22

t2 = a.^2;
t3 = b.^2;
t4 = c.^2;
t5 = -theta_2;
t6 = -t2;
t7 = -t3;
t8 = psi+t5;
t11 = t2.*t3.*4.0;
t9 = cos(t8);
t10 = sin(t8);
t12 = c.*t9;
t13 = t12.*2.0;
t14 = l_1+t12;
t15 = l_1+t13;
t16 = l_1.*t15;
t17 = t3+t4+t6+t16;
t18 = t4+t6+t7+t16;
t19 = (t2+t3-t4-t16).^2;
t20 = -t19;
t21 = t11+t20;
t22 = sqrt(t21);
f = c.*cos(theta_2).*(t9+(t10.*(t14.*t17+c.*t10.*t22))./(t14.*t22+c.*t10.*t17));
